#server.port: 8080
server.port: 9103

#account-service-uri: "http://localhost:9101"
#contact-service-uri: "http://localhost:9102"
external: 
  service: 
    uri: 
      account: "http://localhost:9101"
      contact: "http://localhost:9102"

spring: 
 data: 
  mongodb: 
   host: localhost
   port: 27017
   database: contact_activity_service
